# Generated by Django 5.2 on 2025-08-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Submission', 'verbose_name_plural': 'Contact Submissions'},
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
