# Generated by Django 5.2 on 2025-08-14 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_app', '0003_visitorregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorRegistration',
        ),
    ]
